# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_hwpr_wrappers", use_symbols = TRUE, package_name = "hwpr")

#' @docType package
#' @usage NULL
#' @useDynLib hwpr, .registration = TRUE
NULL

HWPReader <- new.env(parent = emptyenv())

HWPReader$new <- function(path) .Call(wrap__HWPReader__new, path)

HWPReader$find_all <- function() .Call(wrap__HWPReader__find_all, self)

HWPReader$find_all2 <- function() .Call(wrap__HWPReader__find_all2, self)

HWPReader$find_all3 <- function() .Call(wrap__HWPReader__find_all3, self)

#' @export
`$.HWPReader` <- function (self, name) { func <- HWPReader[[name]]; environment(func) <- environment(); func }

#' @export
`[[.HWPReader` <- `$.HWPReader`


# nolint end
