# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_hwpr_wrappers", use_symbols = TRUE, package_name = "hwpr")

#' @docType package
#' @usage NULL
#' @useDynLib hwpr, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
RVersion <- new.env(parent = emptyenv())

RVersion$majer <- function() .Call(wrap__RVersion__majer, self)

#' @rdname RVersion
#' @usage NULL
#' @export
`$.RVersion` <- function (self, name) { func <- RVersion[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RVersion` <- `$.RVersion`


# nolint end
